version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: DaCFood
        ports:
            - "5432:5432"
        networks:
            - logicloth-network
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            retries: 10
            start_period: 10s
            timeout: 3s
#        command: >
#            bash -c '
#                chmod +x /docker-entrypoint-initdb.d/run.sh;
#                /docker-entrypoint-initdb.d/run.sh;
#            '

    tomcat-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        networks:
            - logicloth-network
        depends_on:
            - postgres

    golang:
        build:
            context: ./upload-api
            dockerfile: Dockerfile
        ports:
            - "3030:3030"
        volumes:
            - ./upload-api:/app
        restart: always
        networks:
            - logicloth-network
        depends_on:
            - tomcat-app

networks:
  logicloth-network:
    name: logicloth-network

volumes:
    postgres_data: