version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: DaCFood
        ports:
            - "5432:5432"
        networks:
            - logicloth-network
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            retries: 10
            start_period: 10s
            timeout: 3s

    postgres.configurator:
        image: postgres:latest
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        depends_on:
            postgres:
                condition: service_healthy
        command: >
            bash -c '
            until pg_isready -h postgres -U postgres -W postgres; do
                echo "Waiting for postgres service to be ready...";
                sleep 5;
            done;
            psql -h postgres -U postgres -d DaCFood -a -f /docker-entrypoint-initdb.d/postgres.sql;
            echo "All done!";
            '
        networks:
            - logicloth-network

    tomcat-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        networks:
            - logicloth-network
        depends_on:
            - postgres

    golang:
        build:
            context: ./upload-api
            dockerfile: Dockerfile
        ports:
            - "3030:3030"
        volumes:
            - ./upload-api:/app
        restart: always
        networks:
            - logicloth-network
        depends_on:
            - tomcat-app

networks:
  logicloth-network:
    name: logicloth-network

volumes:
    postgres_data: